### PR TITLE
Update init_with_array documentation

### PR DESCRIPTION
**Pull request by rleonid**
I thought that I was going to have more to say, but this is all that I found.

### CODE REVIEW

**Comment by aantron** [comment]
Thanks, oops. What's the right way to handle this? I merge this PR into my 3-commit PR and make it a 4-commit PR, or just incorporate the change into the first commit and rebase the others?

**Comment by rleonid** [comment]
Actually, let's merge your 3 PR's first and then just merge this into master.
Let me finish reviewing the last 2.

**Comment by aantron** [comment]
Ok. In the meantime, I thought of a silly way to deal with this kind of PR that doesn't introduce an extra commit just for a typo, while still getting a nice purple "merged" icon on GitHub.

1. Merge this into the other PR and update it, this gets the purple icon.
2. Then, squash it in that PR.

A bit ridiculous, but should work, in theory :)

**Comment by rleonid** [comment]
[This](https://xkcd.com/1597/) is appropriate.

**Comment by aantron** [comment]
:laughing:

**Pull request closed without merging**
