### PR TITLE
Bump version to 1.0.0

### PR DESCRIPTION
**Pull request by aantron**
Changelog up for review; to be merged after the other PRs.

### CODE REVIEW

**Comment by rleonid** [comment]
Excellent, :+1:

**Comment by aantron** [comment]
This doesn't have a release date in the changelog, since we are "soft" blocked on ocveralls. I wanted to merge it after #73. `git push -f`?

**Comment by rleonid** [comment]
Woops. Yea, let's do a git push when that is unblocked. We're waiting for `ocveralls` to be updated in `opam`?

**Comment by aantron** [comment]
Yes. It's not necessary, but it would be nice, since then we could be sure that our packaging in 1.0.0 is compatible with one released version of ocveralls. As of now, the only way to use any released ocveralls is with the original Bisect or with Bisect_ppx <= 0.2.6. https://github.com/sagotch/ocveralls/pull/12

Do you think it's better to just go ahead?

**Comment by rleonid** [comment]
I don't mind waiting, gives us time to prepare.

**Pull request merged**
