### PR TITLE
Toplevel support

### PR DESCRIPTION
**Pull request by rleonid**
@smondet now `#require "bisect_ppx.runtime";;` works fine in the toploop. Does this address #13 ?

### CODE REVIEW

**Comment by smondet** [comment]
LGTM!

`bisect_ppx.runtime` works well for my use case.

`bisect_ppx` itself is still failing on the toplevel, it would be nice to still be robust is the package gets loaded by people:

```
# #require "bisect_ppx";;
/Users/sebastienmondet/.opam/4.02.1/lib/bisect_ppx: added to search path
/Users/sebastienmondet/.opam/4.02.1/lib/bisect_ppx/bisect.cma: loaded
/Users/sebastienmondet/.opam/4.02.1/lib/bisect_ppx/bisectThread.cmo: loaded
/Users/sebastienmondet/.opam/4.02.1/lib/bisect_ppx/./bisect_ppx.byte: activated
# let x = 42 ;;
Error: I/O error: //toplevel//: No such file or directory
```

**Comment by rleonid** [comment]
I agree that would be a very useful warning. Any idea's on how to implement it?
It's not the actual loading of the runtime that's the problem, it's the activating of the `bisect_ppx.byte` to perform AST mapping.

**Comment by smondet** [comment]
`bisect_ppx` could just ignore the toplevel silently?

**Comment by rleonid** [comment]
Details? How would `bisect_ppx.byte` know which process (ocaml or ocamlc) is invoking it?

Or do you mean something different?

**Comment by smondet** [comment]
I mean that when the file is `//toplevel//` just do nothing, copy the AST to the next `ppx`.

**Comment by rleonid** [comment]
Ok, that seems reasonable.

**Comment by rleonid** [comment]
With this change, do we still need a separate runtime lib, since the two packages would be pretty much the same?
`bisect_ppx.runtime` just wouldn't invoke the `ppx` mapper ?

**Comment by smondet** [comment]
I think it's cleaner to have the `bisect_ppx.runtime` package (maybe you want to instrument your library, but not you tests and still compile them).

**Comment by rleonid** [comment]
This fixes #13.

**Pull request merged**
