### PR TITLE
Update appearance of HTML reports

### PR DESCRIPTION
**Pull request by aantron**
See the commit message. I'm also thinking about adding optional syntax highlighting, when a highlighter is available.

This PR is more a proposal than something complete. Would be very interested to hear/see how you think the reports should look.

---

**Before**:

old-html

---
---
---

**After**:

new-html

### CODE REVIEW

**Comment by c-cube** [comment]
This looks nice!

**Comment by rleonid** [comment]
This is looks great; no reservations about making the switch or proceeding with these choices.

I noticed a turquoise color for a line, how is that different from a yellow?

**Comment by aantron** [comment]
That's a line that got clicked on. It's a direct link to that line (`#L79`), and the line is highlighted in some garish color meant to stand out from the others. I'm not necessarily happy about the specific color, but I gave myself finite time to tweak them, and ran out. If you have any suggestions, I will be happy to change it, or go ahead and do so yourself :)

**Comment by aantron** [comment]
Perhaps a little CSS animation is a better choice both to attract attention to the clicked line, and to disappear and not be annoying afterwards, once the attention is on it... Let me try.

**Comment by aantron** [comment]
What about this? I also took the opportunity to make the navbar lines a lot fatter. They were difficult to click on.

navhighlight

**Comment by rleonid** [comment]
Haven't tested, but looks good. To the extent possible with the CSS animation, would it be easy to 'center' to that line when the navbar line is clicked?

**Comment by aantron** [comment]
I don't think it's possible with CSS.

But we already have a bit of JS here, so I'll experiment with a script that
- Scrolls the viewport when the navbar is clicked, as you suggest, but aligns the line so that it is adjacent to where the mouse pointer was (if possible). I'll compare it to centering.
- Doesn't scroll the viewport when clicking on a line number, but highlights it briefly to hint that the URL has changed. The current scrolling is a bit annoying in this case.

I was also thinking about just making the whole navbar clickable using JS. Then, it doesn't matter how fat the indicators are, as long as they are visible, since there won't be any problem with trying to hit them.

**Comment by aantron** [comment]
Now like this:

highlight2

**Comment by rleonid** [comment]
Looks good.

**Pull request merged**
