### PR TITLE
Allow exclusion of entire files; files by regex.

### PR DESCRIPTION
**Pull request by aantron**
@solongordon @rgrinberg this change gives syntax as below, for excluding specific whole files, and whole files by pattern:

```
file "specific_test.ml"
file regexp "test_.*"
```

Files excluded in this way don't get instrumented at all, and don't appear in the coverage report. You can also combine the file regexp with the old top-level value exclusions to do things like

```
file regexp "src/.*" [ regexp "test_" ]
```

to exclude all top-level values beginning with `test_` in all files in `src/`.

Let me know if this addresses #89 sufficiently. If so, will adjust documentation and merge in.

### CODE REVIEW

**Comment by solongordon** [comment]
This looks great! Exactly the functionality we were looking for. Thanks for addressing the feature request.

**Comment by rgrinberg** [comment]
:100: Don't forget to mention it's Str's regex syntax.

**Comment by aantron** [comment]
Sorry about the coveralls spam. :(

**Comment by aantron** [comment]
This is now installable from OPAM as `bisect_ppx` 1.1.0.

**Pull request closed without merging**
